### ISSUE TITLE
NPCLib Error

### ISSUE THREAD

**Issue by KroterPvP** [InventivetalentDev/NPCLib#2]
NPCLib gives me this log error in console:

```
[16:17:15 ERROR]: Could not load 'plugins\NPCLib_v1.8.6.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: de/inventivegames/packetlistener/handler/PacketHandler
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:739) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: de/inventivegames/packetlistener/handler/PacketHandler
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: de.inventivegames.packetlistener.handler.PacketHandler
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-76236cb-62a2169]
        ... 14 more
```

**Comment by InventivetalentDev** [comment]
Is PacketListenerAPI installed on your server?

**Comment by KroterPvP** [comment]
Yes

**Comment by KroterPvP** [comment]
Yes it is. I decided to uninstall the plugin and don't put it on my server. If you want and can help me please do it and tell it to me! 
Thanks!

**Comment by InventivetalentDev** [comment]
Please install an older PacketListenerAPI version than 3.4.3. The de.inventvegames.\* packages were removed in 3.4.3. (Or wait for the new NPCLib version)
